// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AggregateAndProofRequestAltairVersion.
const (
	AggregateAndProofRequestAltairVersionALTAIR AggregateAndProofRequestAltairVersion = "ALTAIR"
)

// Valid indicates whether the value is a known member of the AggregateAndProofRequestAltairVersion enum.
func (e AggregateAndProofRequestAltairVersion) Valid() bool {
	switch e {
	case AggregateAndProofRequestAltairVersionALTAIR:
		return true
	default:
		return false
	}
}

// Defines values for AggregateAndProofRequestBellatrixVersion.
const (
	AggregateAndProofRequestBellatrixVersionBELLATRIX AggregateAndProofRequestBellatrixVersion = "BELLATRIX"
)

// Valid indicates whether the value is a known member of the AggregateAndProofRequestBellatrixVersion enum.
func (e AggregateAndProofRequestBellatrixVersion) Valid() bool {
	switch e {
	case AggregateAndProofRequestBellatrixVersionBELLATRIX:
		return true
	default:
		return false
	}
}

// Defines values for AggregateAndProofRequestCapellaVersion.
const (
	AggregateAndProofRequestCapellaVersionCAPELLA AggregateAndProofRequestCapellaVersion = "CAPELLA"
)

// Valid indicates whether the value is a known member of the AggregateAndProofRequestCapellaVersion enum.
func (e AggregateAndProofRequestCapellaVersion) Valid() bool {
	switch e {
	case AggregateAndProofRequestCapellaVersionCAPELLA:
		return true
	default:
		return false
	}
}

// Defines values for AggregateAndProofRequestDenebVersion.
const (
	AggregateAndProofRequestDenebVersionDENEB AggregateAndProofRequestDenebVersion = "DENEB"
)

// Valid indicates whether the value is a known member of the AggregateAndProofRequestDenebVersion enum.
func (e AggregateAndProofRequestDenebVersion) Valid() bool {
	switch e {
	case AggregateAndProofRequestDenebVersionDENEB:
		return true
	default:
		return false
	}
}

// Defines values for AggregateAndProofRequestElectraVersion.
const (
	AggregateAndProofRequestElectraVersionELECTRA AggregateAndProofRequestElectraVersion = "ELECTRA"
)

// Valid indicates whether the value is a known member of the AggregateAndProofRequestElectraVersion enum.
func (e AggregateAndProofRequestElectraVersion) Valid() bool {
	switch e {
	case AggregateAndProofRequestElectraVersionELECTRA:
		return true
	default:
		return false
	}
}

// Defines values for AggregateAndProofRequestFuluVersion.
const (
	AggregateAndProofRequestFuluVersionFULU AggregateAndProofRequestFuluVersion = "FULU"
)

// Valid indicates whether the value is a known member of the AggregateAndProofRequestFuluVersion enum.
func (e AggregateAndProofRequestFuluVersion) Valid() bool {
	switch e {
	case AggregateAndProofRequestFuluVersionFULU:
		return true
	default:
		return false
	}
}

// Defines values for AggregateAndProofRequestPhase0Version.
const (
	AggregateAndProofRequestPhase0VersionPHASE0 AggregateAndProofRequestPhase0Version = "PHASE0"
)

// Valid indicates whether the value is a known member of the AggregateAndProofRequestPhase0Version enum.
func (e AggregateAndProofRequestPhase0Version) Valid() bool {
	switch e {
	case AggregateAndProofRequestPhase0VersionPHASE0:
		return true
	default:
		return false
	}
}

// Defines values for AggregateAndProofSigningType.
const (
	AGGREGATEANDPROOF AggregateAndProofSigningType = "AGGREGATE_AND_PROOF"
)

// Valid indicates whether the value is a known member of the AggregateAndProofSigningType enum.
func (e AggregateAndProofSigningType) Valid() bool {
	switch e {
	case AGGREGATEANDPROOF:
		return true
	default:
		return false
	}
}

// Defines values for AggregateAndProofSigningV2Type.
const (
	AGGREGATEANDPROOFV2 AggregateAndProofSigningV2Type = "AGGREGATE_AND_PROOF_V2"
)

// Valid indicates whether the value is a known member of the AggregateAndProofSigningV2Type enum.
func (e AggregateAndProofSigningV2Type) Valid() bool {
	switch e {
	case AGGREGATEANDPROOFV2:
		return true
	default:
		return false
	}
}

// Defines values for AggregationSlotSigningType.
const (
	AGGREGATIONSLOT AggregationSlotSigningType = "AGGREGATION_SLOT"
)

// Valid indicates whether the value is a known member of the AggregationSlotSigningType enum.
func (e AggregationSlotSigningType) Valid() bool {
	switch e {
	case AGGREGATIONSLOT:
		return true
	default:
		return false
	}
}

// Defines values for AttestationSigningType.
const (
	ATTESTATION AttestationSigningType = "ATTESTATION"
)

// Valid indicates whether the value is a known member of the AttestationSigningType enum.
func (e AttestationSigningType) Valid() bool {
	switch e {
	case ATTESTATION:
		return true
	default:
		return false
	}
}

// Defines values for BeaconBlockSigningType.
const (
	BLOCKV2 BeaconBlockSigningType = "BLOCK_V2"
)

// Valid indicates whether the value is a known member of the BeaconBlockSigningType enum.
func (e BeaconBlockSigningType) Valid() bool {
	switch e {
	case BLOCKV2:
		return true
	default:
		return false
	}
}

// Defines values for BlockRequestAltairVersion.
const (
	BlockRequestAltairVersionALTAIR BlockRequestAltairVersion = "ALTAIR"
)

// Valid indicates whether the value is a known member of the BlockRequestAltairVersion enum.
func (e BlockRequestAltairVersion) Valid() bool {
	switch e {
	case BlockRequestAltairVersionALTAIR:
		return true
	default:
		return false
	}
}

// Defines values for BlockRequestBellatrixVersion.
const (
	BlockRequestBellatrixVersionBELLATRIX BlockRequestBellatrixVersion = "BELLATRIX"
)

// Valid indicates whether the value is a known member of the BlockRequestBellatrixVersion enum.
func (e BlockRequestBellatrixVersion) Valid() bool {
	switch e {
	case BlockRequestBellatrixVersionBELLATRIX:
		return true
	default:
		return false
	}
}

// Defines values for BlockRequestCapellaVersion.
const (
	BlockRequestCapellaVersionCAPELLA BlockRequestCapellaVersion = "CAPELLA"
)

// Valid indicates whether the value is a known member of the BlockRequestCapellaVersion enum.
func (e BlockRequestCapellaVersion) Valid() bool {
	switch e {
	case BlockRequestCapellaVersionCAPELLA:
		return true
	default:
		return false
	}
}

// Defines values for BlockRequestDenebVersion.
const (
	BlockRequestDenebVersionDENEB BlockRequestDenebVersion = "DENEB"
)

// Valid indicates whether the value is a known member of the BlockRequestDenebVersion enum.
func (e BlockRequestDenebVersion) Valid() bool {
	switch e {
	case BlockRequestDenebVersionDENEB:
		return true
	default:
		return false
	}
}

// Defines values for BlockRequestElectraVersion.
const (
	BlockRequestElectraVersionELECTRA BlockRequestElectraVersion = "ELECTRA"
)

// Valid indicates whether the value is a known member of the BlockRequestElectraVersion enum.
func (e BlockRequestElectraVersion) Valid() bool {
	switch e {
	case BlockRequestElectraVersionELECTRA:
		return true
	default:
		return false
	}
}

// Defines values for BlockRequestFuluVersion.
const (
	BlockRequestFuluVersionFULU BlockRequestFuluVersion = "FULU"
)

// Valid indicates whether the value is a known member of the BlockRequestFuluVersion enum.
func (e BlockRequestFuluVersion) Valid() bool {
	switch e {
	case BlockRequestFuluVersionFULU:
		return true
	default:
		return false
	}
}

// Defines values for BlockRequestPhase0Version.
const (
	BlockRequestPhase0VersionPHASE0 BlockRequestPhase0Version = "PHASE0"
)

// Valid indicates whether the value is a known member of the BlockRequestPhase0Version enum.
func (e BlockRequestPhase0Version) Valid() bool {
	switch e {
	case BlockRequestPhase0VersionPHASE0:
		return true
	default:
		return false
	}
}

// Defines values for BlockSigningType.
const (
	BLOCK BlockSigningType = "BLOCK"
)

// Valid indicates whether the value is a known member of the BlockSigningType enum.
func (e BlockSigningType) Valid() bool {
	switch e {
	case BLOCK:
		return true
	default:
		return false
	}
}

// Defines values for DepositSigningType.
const (
	DEPOSIT DepositSigningType = "DEPOSIT"
)

// Valid indicates whether the value is a known member of the DepositSigningType enum.
func (e DepositSigningType) Valid() bool {
	switch e {
	case DEPOSIT:
		return true
	default:
		return false
	}
}

// Defines values for RandaoRevealSigningType.
const (
	RANDAOREVEAL RandaoRevealSigningType = "RANDAO_REVEAL"
)

// Valid indicates whether the value is a known member of the RandaoRevealSigningType enum.
func (e RandaoRevealSigningType) Valid() bool {
	switch e {
	case RANDAOREVEAL:
		return true
	default:
		return false
	}
}

// Defines values for SyncCommitteeContributionAndProofSigningType.
const (
	SYNCCOMMITTEECONTRIBUTIONANDPROOF SyncCommitteeContributionAndProofSigningType = "SYNC_COMMITTEE_CONTRIBUTION_AND_PROOF"
)

// Valid indicates whether the value is a known member of the SyncCommitteeContributionAndProofSigningType enum.
func (e SyncCommitteeContributionAndProofSigningType) Valid() bool {
	switch e {
	case SYNCCOMMITTEECONTRIBUTIONANDPROOF:
		return true
	default:
		return false
	}
}

// Defines values for SyncCommitteeMessageSigningType.
const (
	SYNCCOMMITTEEMESSAGE SyncCommitteeMessageSigningType = "SYNC_COMMITTEE_MESSAGE"
)

// Valid indicates whether the value is a known member of the SyncCommitteeMessageSigningType enum.
func (e SyncCommitteeMessageSigningType) Valid() bool {
	switch e {
	case SYNCCOMMITTEEMESSAGE:
		return true
	default:
		return false
	}
}

// Defines values for SyncCommitteeSelectionProofSigningType.
const (
	SYNCCOMMITTEESELECTIONPROOF SyncCommitteeSelectionProofSigningType = "SYNC_COMMITTEE_SELECTION_PROOF"
)

// Valid indicates whether the value is a known member of the SyncCommitteeSelectionProofSigningType enum.
func (e SyncCommitteeSelectionProofSigningType) Valid() bool {
	switch e {
	case SYNCCOMMITTEESELECTIONPROOF:
		return true
	default:
		return false
	}
}

// Defines values for ValidatorRegistrationSigningType.
const (
	VALIDATORREGISTRATION ValidatorRegistrationSigningType = "VALIDATOR_REGISTRATION"
)

// Valid indicates whether the value is a known member of the ValidatorRegistrationSigningType enum.
func (e ValidatorRegistrationSigningType) Valid() bool {
	switch e {
	case VALIDATORREGISTRATION:
		return true
	default:
		return false
	}
}

// Defines values for VoluntaryExitSigningType.
const (
	VOLUNTARYEXIT VoluntaryExitSigningType = "VOLUNTARY_EXIT"
)

// Valid indicates whether the value is a known member of the VoluntaryExitSigningType enum.
func (e VoluntaryExitSigningType) Valid() bool {
	switch e {
	case VOLUNTARYEXIT:
		return true
	default:
		return false
	}
}

// AggregateAndProofElectra defines model for AggregateAndProofElectra.
type AggregateAndProofElectra struct {
	Aggregate       *AttestationElectra `json:"aggregate,omitempty"`
	AggregatorIndex *string             `json:"aggregator_index,omitempty"`

	// SelectionProof Bytes96 hexadecimal
	SelectionProof *string `json:"selection_proof,omitempty"`
}

// AggregateAndProofPhase0 defines model for AggregateAndProofPhase0.
type AggregateAndProofPhase0 struct {
	Aggregate       *AttestationPhase0 `json:"aggregate,omitempty"`
	AggregatorIndex *string            `json:"aggregator_index,omitempty"`

	// SelectionProof Bytes96 hexadecimal
	SelectionProof *string `json:"selection_proof,omitempty"`
}

// AggregateAndProofRequest defines model for AggregateAndProofRequest.
type AggregateAndProofRequest struct {
	AggregateAndProof AggregateAndProofRequest_AggregateAndProof `json:"aggregate_and_proof"`
}

// AggregateAndProofRequest_AggregateAndProof defines model for AggregateAndProofRequest.AggregateAndProof.
type AggregateAndProofRequest_AggregateAndProof struct {
	union json.RawMessage
}

// AggregateAndProofRequestAltair defines model for AggregateAndProofRequestAltair.
type AggregateAndProofRequestAltair struct {
	Data AggregateAndProofPhase0 `json:"data"`

	// Version version to identify AggregateAndProof request type.
	Version AggregateAndProofRequestAltairVersion `json:"version"`
}

// AggregateAndProofRequestAltairVersion version to identify AggregateAndProof request type.
type AggregateAndProofRequestAltairVersion string

// AggregateAndProofRequestBellatrix defines model for AggregateAndProofRequestBellatrix.
type AggregateAndProofRequestBellatrix struct {
	Data AggregateAndProofPhase0 `json:"data"`

	// Version version to identify AggregateAndProof request type.
	Version AggregateAndProofRequestBellatrixVersion `json:"version"`
}

// AggregateAndProofRequestBellatrixVersion version to identify AggregateAndProof request type.
type AggregateAndProofRequestBellatrixVersion string

// AggregateAndProofRequestCapella defines model for AggregateAndProofRequestCapella.
type AggregateAndProofRequestCapella struct {
	Data AggregateAndProofPhase0 `json:"data"`

	// Version version to identify AggregateAndProof request type.
	Version AggregateAndProofRequestCapellaVersion `json:"version"`
}

// AggregateAndProofRequestCapellaVersion version to identify AggregateAndProof request type.
type AggregateAndProofRequestCapellaVersion string

// AggregateAndProofRequestDeneb defines model for AggregateAndProofRequestDeneb.
type AggregateAndProofRequestDeneb struct {
	Data AggregateAndProofPhase0 `json:"data"`

	// Version version to identify AggregateAndProof request type.
	Version AggregateAndProofRequestDenebVersion `json:"version"`
}

// AggregateAndProofRequestDenebVersion version to identify AggregateAndProof request type.
type AggregateAndProofRequestDenebVersion string

// AggregateAndProofRequestElectra defines model for AggregateAndProofRequestElectra.
type AggregateAndProofRequestElectra struct {
	Data AggregateAndProofElectra `json:"data"`

	// Version version to identify AggregateAndProof request type.
	Version AggregateAndProofRequestElectraVersion `json:"version"`
}

// AggregateAndProofRequestElectraVersion version to identify AggregateAndProof request type.
type AggregateAndProofRequestElectraVersion string

// AggregateAndProofRequestFulu defines model for AggregateAndProofRequestFulu.
type AggregateAndProofRequestFulu struct {
	Data AggregateAndProofElectra `json:"data"`

	// Version version to identify AggregateAndProof request type.
	Version AggregateAndProofRequestFuluVersion `json:"version"`
}

// AggregateAndProofRequestFuluVersion version to identify AggregateAndProof request type.
type AggregateAndProofRequestFuluVersion string

// AggregateAndProofRequestPhase0 defines model for AggregateAndProofRequestPhase0.
type AggregateAndProofRequestPhase0 struct {
	Data AggregateAndProofPhase0 `json:"data"`

	// Version version to identify AggregateAndProof request type.
	Version AggregateAndProofRequestPhase0Version `json:"version"`
}

// AggregateAndProofRequestPhase0Version version to identify AggregateAndProof request type.
type AggregateAndProofRequestPhase0Version string

// AggregateAndProofSigning defines model for AggregateAndProofSigning.
type AggregateAndProofSigning struct {
	AggregateAndProof AggregateAndProofPhase0 `json:"aggregate_and_proof"`
	ForkInfo          struct {
		Fork Fork `json:"fork"`

		// GenesisValidatorsRoot Genesis Validators Root in hex string format.
		GenesisValidatorsRoot string `json:"genesis_validators_root"`
	} `json:"fork_info"`

	// SigningRoot signing root for optional verification if field present
	SigningRoot *string `json:"signingRoot,omitempty"`

	// Type Signing Request type
	Type AggregateAndProofSigningType `json:"type"`
}

// AggregateAndProofSigningType Signing Request type
type AggregateAndProofSigningType string

// AggregateAndProofSigningV2 defines model for AggregateAndProofSigningV2.
type AggregateAndProofSigningV2 struct {
	AggregateAndProof AggregateAndProofSigningV2_AggregateAndProof `json:"aggregate_and_proof"`
	ForkInfo          struct {
		Fork Fork `json:"fork"`

		// GenesisValidatorsRoot Genesis Validators Root in hex string format.
		GenesisValidatorsRoot string `json:"genesis_validators_root"`
	} `json:"fork_info"`

	// SigningRoot signing root for optional verification if field present
	SigningRoot *string `json:"signingRoot,omitempty"`

	// Type Signing Request type
	Type AggregateAndProofSigningV2Type `json:"type"`
}

// AggregateAndProofSigningV2_AggregateAndProof defines model for AggregateAndProofSigningV2.AggregateAndProof.
type AggregateAndProofSigningV2_AggregateAndProof struct {
	union json.RawMessage
}

// AggregateAndProofSigningV2Type Signing Request type
type AggregateAndProofSigningV2Type string

// AggregationSlotSigning defines model for AggregationSlotSigning.
type AggregationSlotSigning struct {
	AggregationSlot struct {
		Slot *string `json:"slot,omitempty"`
	} `json:"aggregation_slot"`
	ForkInfo struct {
		Fork Fork `json:"fork"`

		// GenesisValidatorsRoot Genesis Validators Root in hex string format.
		GenesisValidatorsRoot string `json:"genesis_validators_root"`
	} `json:"fork_info"`

	// SigningRoot signing root for optional verification if field present
	SigningRoot *string `json:"signingRoot,omitempty"`

	// Type Signing Request type
	Type AggregationSlotSigningType `json:"type"`
}

// AggregationSlotSigningType Signing Request type
type AggregationSlotSigningType string

// AttestationData defines model for AttestationData.
type AttestationData struct {
	BeaconBlockRoot *string     `json:"beacon_block_root,omitempty"`
	Index           *string     `json:"index,omitempty"`
	Slot            *string     `json:"slot,omitempty"`
	Source          *Checkpoint `json:"source,omitempty"`
	Target          *Checkpoint `json:"target,omitempty"`
}

// AttestationElectra defines model for AttestationElectra.
type AttestationElectra struct {
	AggregationBits *string          `json:"aggregation_bits,omitempty"`
	CommitteeBits   *string          `json:"committee_bits,omitempty"`
	Data            *AttestationData `json:"data,omitempty"`
	Signature       *string          `json:"signature,omitempty"`
}

// AttestationPhase0 defines model for AttestationPhase0.
type AttestationPhase0 struct {
	AggregationBits *string          `json:"aggregation_bits,omitempty"`
	Data            *AttestationData `json:"data,omitempty"`
	Signature       *string          `json:"signature,omitempty"`
}

// AttestationSigning defines model for AttestationSigning.
type AttestationSigning struct {
	Attestation AttestationData `json:"attestation"`
	ForkInfo    struct {
		Fork Fork `json:"fork"`

		// GenesisValidatorsRoot Genesis Validators Root in hex string format.
		GenesisValidatorsRoot string `json:"genesis_validators_root"`
	} `json:"fork_info"`

	// SigningRoot signing root for optional verification if field present
	SigningRoot *string `json:"signingRoot,omitempty"`

	// Type Signing Request type
	Type AttestationSigningType `json:"type"`
}

// AttestationSigningType Signing Request type
type AttestationSigningType string

// AttesterSlashing defines model for AttesterSlashing.
type AttesterSlashing struct {
	Attestation1 *IndexedAttestation `json:"attestation_1,omitempty"`
	Attestation2 *IndexedAttestation `json:"attestation_2,omitempty"`
}

// BeaconBlock defines model for BeaconBlock.
type BeaconBlock struct {
	Body          *BeaconBlockBody `json:"body,omitempty"`
	ParentRoot    *string          `json:"parent_root,omitempty"`
	ProposerIndex *string          `json:"proposer_index,omitempty"`
	Slot          *string          `json:"slot,omitempty"`
	StateRoot     *string          `json:"state_root,omitempty"`
}

// BeaconBlockAltair defines model for BeaconBlockAltair.
type BeaconBlockAltair struct {
	Body          *BeaconBlockBodyAltair `json:"body,omitempty"`
	ParentRoot    *string                `json:"parent_root,omitempty"`
	ProposerIndex *string                `json:"proposer_index,omitempty"`
	Slot          *string                `json:"slot,omitempty"`
	StateRoot     *string                `json:"state_root,omitempty"`
}

// BeaconBlockBody defines model for BeaconBlockBody.
type BeaconBlockBody struct {
	Attestations      *[]AttestationPhase0 `json:"attestations,omitempty"`
	AttesterSlashings *[]AttesterSlashing  `json:"attester_slashings,omitempty"`
	Deposits          *[]Deposit           `json:"deposits,omitempty"`
	Eth1Data          *Eth1Data            `json:"eth1_data,omitempty"`

	// Graffiti Bytes32 hexadecimal
	Graffiti          *string                `json:"graffiti,omitempty"`
	ProposerSlashings *[]ProposerSlashing    `json:"proposer_slashings,omitempty"`
	RandaoReveal      *string                `json:"randao_reveal,omitempty"`
	VoluntaryExits    *[]SignedVoluntaryExit `json:"voluntary_exits,omitempty"`
}

// BeaconBlockBodyAltair defines model for BeaconBlockBodyAltair.
type BeaconBlockBodyAltair struct {
	Attestations      *[]AttestationPhase0 `json:"attestations,omitempty"`
	AttesterSlashings *[]AttesterSlashing  `json:"attester_slashings,omitempty"`
	Deposits          *[]Deposit           `json:"deposits,omitempty"`
	Eth1Data          *Eth1Data            `json:"eth1_data,omitempty"`

	// Graffiti Bytes32 hexadecimal
	Graffiti          *string                `json:"graffiti,omitempty"`
	ProposerSlashings *[]ProposerSlashing    `json:"proposer_slashings,omitempty"`
	RandaoReveal      *string                `json:"randao_reveal,omitempty"`
	SyncAggregate     *SyncAggregate         `json:"sync_aggregate,omitempty"`
	VoluntaryExits    *[]SignedVoluntaryExit `json:"voluntary_exits,omitempty"`
}

// BeaconBlockHeader defines model for BeaconBlockHeader.
type BeaconBlockHeader struct {
	// BodyRoot Bytes32 hexadecimal
	BodyRoot *string `json:"body_root,omitempty"`

	// ParentRoot Bytes32 hexadecimal
	ParentRoot    *string `json:"parent_root,omitempty"`
	ProposerIndex *string `json:"proposer_index,omitempty"`
	Slot          *string `json:"slot,omitempty"`

	// StateRoot Bytes32 hexadecimal
	StateRoot *string `json:"state_root,omitempty"`
}

// BeaconBlockRequest defines model for BeaconBlockRequest.
type BeaconBlockRequest struct {
	BeaconBlock BeaconBlockRequest_BeaconBlock `json:"beacon_block"`
}

// BeaconBlockRequest_BeaconBlock defines model for BeaconBlockRequest.BeaconBlock.
type BeaconBlockRequest_BeaconBlock struct {
	union json.RawMessage
}

// BeaconBlockSigning defines model for BeaconBlockSigning.
type BeaconBlockSigning struct {
	BeaconBlock BeaconBlockSigning_BeaconBlock `json:"beacon_block"`
	ForkInfo    struct {
		Fork Fork `json:"fork"`

		// GenesisValidatorsRoot Genesis Validators Root in hex string format.
		GenesisValidatorsRoot string `json:"genesis_validators_root"`
	} `json:"fork_info"`

	// SigningRoot signing root for optional verification if field present
	SigningRoot *string `json:"signingRoot,omitempty"`

	// Type Signing Request type
	Type BeaconBlockSigningType `json:"type"`
}

// BeaconBlockSigning_BeaconBlock defines model for BeaconBlockSigning.BeaconBlock.
type BeaconBlockSigning_BeaconBlock struct {
	union json.RawMessage
}

// BeaconBlockSigningType Signing Request type
type BeaconBlockSigningType string

// BlockRequestAltair defines model for BlockRequestAltair.
type BlockRequestAltair struct {
	Block BeaconBlockAltair `json:"block"`

	// Version version to identify block request type.
	Version BlockRequestAltairVersion `json:"version"`
}

// BlockRequestAltairVersion version to identify block request type.
type BlockRequestAltairVersion string

// BlockRequestBellatrix defines model for BlockRequestBellatrix.
type BlockRequestBellatrix struct {
	BlockHeader BeaconBlockHeader `json:"block_header"`

	// Version version to identify block request type.
	Version BlockRequestBellatrixVersion `json:"version"`
}

// BlockRequestBellatrixVersion version to identify block request type.
type BlockRequestBellatrixVersion string

// BlockRequestCapella defines model for BlockRequestCapella.
type BlockRequestCapella struct {
	BlockHeader BeaconBlockHeader `json:"block_header"`

	// Version version to identify block request type.
	Version BlockRequestCapellaVersion `json:"version"`
}

// BlockRequestCapellaVersion version to identify block request type.
type BlockRequestCapellaVersion string

// BlockRequestDeneb defines model for BlockRequestDeneb.
type BlockRequestDeneb struct {
	BlockHeader BeaconBlockHeader `json:"block_header"`

	// Version version to identify block request type.
	Version BlockRequestDenebVersion `json:"version"`
}

// BlockRequestDenebVersion version to identify block request type.
type BlockRequestDenebVersion string

// BlockRequestElectra defines model for BlockRequestElectra.
type BlockRequestElectra struct {
	BlockHeader BeaconBlockHeader `json:"block_header"`

	// Version version to identify block request type.
	Version BlockRequestElectraVersion `json:"version"`
}

// BlockRequestElectraVersion version to identify block request type.
type BlockRequestElectraVersion string

// BlockRequestFulu defines model for BlockRequestFulu.
type BlockRequestFulu struct {
	BlockHeader BeaconBlockHeader `json:"block_header"`

	// Version version to identify block request type.
	Version BlockRequestFuluVersion `json:"version"`
}

// BlockRequestFuluVersion version to identify block request type.
type BlockRequestFuluVersion string

// BlockRequestPhase0 defines model for BlockRequestPhase0.
type BlockRequestPhase0 struct {
	Block BeaconBlock `json:"block"`

	// Version version to identify block request type.
	Version BlockRequestPhase0Version `json:"version"`
}

// BlockRequestPhase0Version version to identify block request type.
type BlockRequestPhase0Version string

// BlockSigning defines model for BlockSigning.
type BlockSigning struct {
	Block    BeaconBlock `json:"block"`
	ForkInfo struct {
		Fork Fork `json:"fork"`

		// GenesisValidatorsRoot Genesis Validators Root in hex string format.
		GenesisValidatorsRoot string `json:"genesis_validators_root"`
	} `json:"fork_info"`

	// SigningRoot signing root for optional verification if field present
	SigningRoot *string `json:"signingRoot,omitempty"`

	// Type Signing Request type
	Type BlockSigningType `json:"type"`
}

// BlockSigningType Signing Request type
type BlockSigningType string

// Checkpoint defines model for Checkpoint.
type Checkpoint struct {
	Epoch *string `json:"epoch,omitempty"`
	Root  *string `json:"root,omitempty"`
}

// ContributionAndProof defines model for ContributionAndProof.
type ContributionAndProof struct {
	AggregatorIndex *string                    `json:"aggregator_index,omitempty"`
	Contribution    *SyncCommitteeContribution `json:"contribution,omitempty"`

	// SelectionProof Bytes96 hexadecimal
	SelectionProof *string `json:"selection_proof,omitempty"`
}

// Deposit defines model for Deposit.
type Deposit struct {
	Data  *DepositData `json:"data,omitempty"`
	Proof *[]string    `json:"proof,omitempty"`
}

// DepositData defines model for DepositData.
type DepositData struct {
	Amount                *string `json:"amount,omitempty"`
	Pubkey                *string `json:"pubkey,omitempty"`
	Signature             *string `json:"signature,omitempty"`
	WithdrawalCredentials *string `json:"withdrawal_credentials,omitempty"`
}

// DepositSigning defines model for DepositSigning.
type DepositSigning struct {
	Deposit struct {
		Amount *string `json:"amount,omitempty"`

		// GenesisForkVersion Bytes4 hexadecimal
		GenesisForkVersion    *string `json:"genesis_fork_version,omitempty"`
		Pubkey                *string `json:"pubkey,omitempty"`
		WithdrawalCredentials *string `json:"withdrawal_credentials,omitempty"`
	} `json:"deposit"`

	// SigningRoot signing root for optional verification if field present
	SigningRoot *string `json:"signingRoot,omitempty"`

	// Type Signing Request type
	Type DepositSigningType `json:"type"`
}

// DepositSigningType Signing Request type
type DepositSigningType string

// Eth1Data defines model for Eth1Data.
type Eth1Data struct {
	BlockHash    *string `json:"block_hash,omitempty"`
	DepositCount *string `json:"deposit_count,omitempty"`
	DepositRoot  *string `json:"deposit_root,omitempty"`
}

// Fork defines model for Fork.
type Fork struct {
	// CurrentVersion Current version of fork
	CurrentVersion *string `json:"current_version,omitempty"`

	// Epoch Epoch value in String format
	Epoch *string `json:"epoch,omitempty"`

	// PreviousVersion Previous version of fork
	PreviousVersion *string `json:"previous_version,omitempty"`
}

// IndexedAttestation defines model for IndexedAttestation.
type IndexedAttestation struct {
	AttestingIndices *[]string        `json:"attesting_indices,omitempty"`
	Data             *AttestationData `json:"data,omitempty"`
	Signature        *string          `json:"signature,omitempty"`
}

// ProposerSlashing defines model for ProposerSlashing.
type ProposerSlashing struct {
	SignedHeader1 *SignedBeaconBlockHeader `json:"signed_header_1,omitempty"`
	SignedHeader2 *SignedBeaconBlockHeader `json:"signed_header_2,omitempty"`
}

// RandaoReveal defines model for RandaoReveal.
type RandaoReveal struct {
	Epoch *string `json:"epoch,omitempty"`
}

// RandaoRevealSigning defines model for RandaoRevealSigning.
type RandaoRevealSigning struct {
	ForkInfo struct {
		Fork Fork `json:"fork"`

		// GenesisValidatorsRoot Genesis Validators Root in hex string format.
		GenesisValidatorsRoot string `json:"genesis_validators_root"`
	} `json:"fork_info"`
	RandaoReveal RandaoReveal `json:"randao_reveal"`

	// SigningRoot signing root for optional verification if field present
	SigningRoot *string `json:"signingRoot,omitempty"`

	// Type Signing Request type
	Type RandaoRevealSigningType `json:"type"`
}

// RandaoRevealSigningType Signing Request type
type RandaoRevealSigningType string

// SignedBeaconBlockHeader defines model for SignedBeaconBlockHeader.
type SignedBeaconBlockHeader struct {
	Message   *BeaconBlockHeader `json:"message,omitempty"`
	Signature *string            `json:"signature,omitempty"`
}

// SignedVoluntaryExit defines model for SignedVoluntaryExit.
type SignedVoluntaryExit struct {
	Message   *VoluntaryExit `json:"message,omitempty"`
	Signature *string        `json:"signature,omitempty"`
}

// Signing defines model for Signing.
type Signing struct {
	ForkInfo struct {
		Fork Fork `json:"fork"`

		// GenesisValidatorsRoot Genesis Validators Root in hex string format.
		GenesisValidatorsRoot string `json:"genesis_validators_root"`
	} `json:"fork_info"`

	// SigningRoot signing root for optional verification if field present
	SigningRoot *string `json:"signingRoot,omitempty"`
}

// SigningResponse defines model for SigningResponse.
type SigningResponse struct {
	// Signature Hex encoded string of signature
	Signature *string `json:"signature,omitempty"`
}

// SyncAggregate defines model for SyncAggregate.
type SyncAggregate struct {
	// SyncCommitteeBits SSZ hexadecimal
	SyncCommitteeBits *string `json:"sync_committee_bits,omitempty"`

	// SyncCommitteeSignature Bytes96 hexadecimal
	SyncCommitteeSignature *string `json:"sync_committee_signature,omitempty"`
}

// SyncAggregatorSelectionData defines model for SyncAggregatorSelectionData.
type SyncAggregatorSelectionData struct {
	Slot              *string `json:"slot,omitempty"`
	SubcommitteeIndex *string `json:"subcommittee_index,omitempty"`
}

// SyncCommitteeContribution defines model for SyncCommitteeContribution.
type SyncCommitteeContribution struct {
	// AggregationBits SSZ hexadecimal
	AggregationBits *string `json:"aggregation_bits,omitempty"`

	// BeaconBlockRoot Bytes32 hexadecimal
	BeaconBlockRoot *string `json:"beacon_block_root,omitempty"`

	// Signature Bytes96 hexadecimal
	Signature         *string `json:"signature,omitempty"`
	Slot              *string `json:"slot,omitempty"`
	SubcommitteeIndex *string `json:"subcommittee_index,omitempty"`
}

// SyncCommitteeContributionAndProofSigning defines model for SyncCommitteeContributionAndProofSigning.
type SyncCommitteeContributionAndProofSigning struct {
	ContributionAndProof ContributionAndProof `json:"contribution_and_proof"`
	ForkInfo             struct {
		Fork Fork `json:"fork"`

		// GenesisValidatorsRoot Genesis Validators Root in hex string format.
		GenesisValidatorsRoot string `json:"genesis_validators_root"`
	} `json:"fork_info"`

	// SigningRoot signing root for optional verification if field present
	SigningRoot *string `json:"signingRoot,omitempty"`

	// Type Signing Request type
	Type SyncCommitteeContributionAndProofSigningType `json:"type"`
}

// SyncCommitteeContributionAndProofSigningType Signing Request type
type SyncCommitteeContributionAndProofSigningType string

// SyncCommitteeMessage defines model for SyncCommitteeMessage.
type SyncCommitteeMessage struct {
	// BeaconBlockRoot Bytes32 hexadecimal
	BeaconBlockRoot *string `json:"beacon_block_root,omitempty"`
	Slot            *string `json:"slot,omitempty"`
}

// SyncCommitteeMessageSigning defines model for SyncCommitteeMessageSigning.
type SyncCommitteeMessageSigning struct {
	ForkInfo struct {
		Fork Fork `json:"fork"`

		// GenesisValidatorsRoot Genesis Validators Root in hex string format.
		GenesisValidatorsRoot string `json:"genesis_validators_root"`
	} `json:"fork_info"`

	// SigningRoot signing root for optional verification if field present
	SigningRoot          *string              `json:"signingRoot,omitempty"`
	SyncCommitteeMessage SyncCommitteeMessage `json:"sync_committee_message"`

	// Type Signing Request type
	Type SyncCommitteeMessageSigningType `json:"type"`
}

// SyncCommitteeMessageSigningType Signing Request type
type SyncCommitteeMessageSigningType string

// SyncCommitteeSelectionProofSigning defines model for SyncCommitteeSelectionProofSigning.
type SyncCommitteeSelectionProofSigning struct {
	ForkInfo struct {
		Fork Fork `json:"fork"`

		// GenesisValidatorsRoot Genesis Validators Root in hex string format.
		GenesisValidatorsRoot string `json:"genesis_validators_root"`
	} `json:"fork_info"`

	// SigningRoot signing root for optional verification if field present
	SigningRoot                 *string                     `json:"signingRoot,omitempty"`
	SyncAggregatorSelectionData SyncAggregatorSelectionData `json:"sync_aggregator_selection_data"`

	// Type Signing Request type
	Type SyncCommitteeSelectionProofSigningType `json:"type"`
}

// SyncCommitteeSelectionProofSigningType Signing Request type
type SyncCommitteeSelectionProofSigningType string

// ValidatorRegistration defines model for ValidatorRegistration.
type ValidatorRegistration struct {
	// FeeRecipient Bytes20 hexadecimal
	FeeRecipient *string `json:"fee_recipient,omitempty"`
	GasLimit     *string `json:"gas_limit,omitempty"`
	Pubkey       *string `json:"pubkey,omitempty"`
	Timestamp    *string `json:"timestamp,omitempty"`
}

// ValidatorRegistrationSigning defines model for ValidatorRegistrationSigning.
type ValidatorRegistrationSigning struct {
	// SigningRoot signing root for optional verification if field present
	SigningRoot *string `json:"signingRoot,omitempty"`

	// Type Signing Request type
	Type                  ValidatorRegistrationSigningType `json:"type"`
	ValidatorRegistration ValidatorRegistration            `json:"validator_registration"`
}

// ValidatorRegistrationSigningType Signing Request type
type ValidatorRegistrationSigningType string

// VoluntaryExit defines model for VoluntaryExit.
type VoluntaryExit struct {
	Epoch          *string `json:"epoch,omitempty"`
	ValidatorIndex *string `json:"validator_index,omitempty"`
}

// VoluntaryExitSigning defines model for VoluntaryExitSigning.
type VoluntaryExitSigning struct {
	ForkInfo struct {
		Fork Fork `json:"fork"`

		// GenesisValidatorsRoot Genesis Validators Root in hex string format.
		GenesisValidatorsRoot string `json:"genesis_validators_root"`
	} `json:"fork_info"`

	// SigningRoot signing root for optional verification if field present
	SigningRoot *string `json:"signingRoot,omitempty"`

	// Type Signing Request type
	Type          VoluntaryExitSigningType `json:"type"`
	VoluntaryExit VoluntaryExit            `json:"voluntary_exit"`
}

// VoluntaryExitSigningType Signing Request type
type VoluntaryExitSigningType string

// AsAggregateAndProofRequestPhase0 returns the union data inside the AggregateAndProofRequest_AggregateAndProof as a AggregateAndProofRequestPhase0
func (t AggregateAndProofRequest_AggregateAndProof) AsAggregateAndProofRequestPhase0() (AggregateAndProofRequestPhase0, error) {
	var body AggregateAndProofRequestPhase0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAggregateAndProofRequestPhase0 overwrites any union data inside the AggregateAndProofRequest_AggregateAndProof as the provided AggregateAndProofRequestPhase0
func (t *AggregateAndProofRequest_AggregateAndProof) FromAggregateAndProofRequestPhase0(v AggregateAndProofRequestPhase0) error {
	v.Version = "PHASE0"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAggregateAndProofRequestPhase0 performs a merge with any union data inside the AggregateAndProofRequest_AggregateAndProof, using the provided AggregateAndProofRequestPhase0
func (t *AggregateAndProofRequest_AggregateAndProof) MergeAggregateAndProofRequestPhase0(v AggregateAndProofRequestPhase0) error {
	v.Version = "PHASE0"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAggregateAndProofRequestAltair returns the union data inside the AggregateAndProofRequest_AggregateAndProof as a AggregateAndProofRequestAltair
func (t AggregateAndProofRequest_AggregateAndProof) AsAggregateAndProofRequestAltair() (AggregateAndProofRequestAltair, error) {
	var body AggregateAndProofRequestAltair
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAggregateAndProofRequestAltair overwrites any union data inside the AggregateAndProofRequest_AggregateAndProof as the provided AggregateAndProofRequestAltair
func (t *AggregateAndProofRequest_AggregateAndProof) FromAggregateAndProofRequestAltair(v AggregateAndProofRequestAltair) error {
	v.Version = "ALTAIR"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAggregateAndProofRequestAltair performs a merge with any union data inside the AggregateAndProofRequest_AggregateAndProof, using the provided AggregateAndProofRequestAltair
func (t *AggregateAndProofRequest_AggregateAndProof) MergeAggregateAndProofRequestAltair(v AggregateAndProofRequestAltair) error {
	v.Version = "ALTAIR"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAggregateAndProofRequestBellatrix returns the union data inside the AggregateAndProofRequest_AggregateAndProof as a AggregateAndProofRequestBellatrix
func (t AggregateAndProofRequest_AggregateAndProof) AsAggregateAndProofRequestBellatrix() (AggregateAndProofRequestBellatrix, error) {
	var body AggregateAndProofRequestBellatrix
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAggregateAndProofRequestBellatrix overwrites any union data inside the AggregateAndProofRequest_AggregateAndProof as the provided AggregateAndProofRequestBellatrix
func (t *AggregateAndProofRequest_AggregateAndProof) FromAggregateAndProofRequestBellatrix(v AggregateAndProofRequestBellatrix) error {
	v.Version = "BELLATRIX"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAggregateAndProofRequestBellatrix performs a merge with any union data inside the AggregateAndProofRequest_AggregateAndProof, using the provided AggregateAndProofRequestBellatrix
func (t *AggregateAndProofRequest_AggregateAndProof) MergeAggregateAndProofRequestBellatrix(v AggregateAndProofRequestBellatrix) error {
	v.Version = "BELLATRIX"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAggregateAndProofRequestCapella returns the union data inside the AggregateAndProofRequest_AggregateAndProof as a AggregateAndProofRequestCapella
func (t AggregateAndProofRequest_AggregateAndProof) AsAggregateAndProofRequestCapella() (AggregateAndProofRequestCapella, error) {
	var body AggregateAndProofRequestCapella
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAggregateAndProofRequestCapella overwrites any union data inside the AggregateAndProofRequest_AggregateAndProof as the provided AggregateAndProofRequestCapella
func (t *AggregateAndProofRequest_AggregateAndProof) FromAggregateAndProofRequestCapella(v AggregateAndProofRequestCapella) error {
	v.Version = "CAPELLA"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAggregateAndProofRequestCapella performs a merge with any union data inside the AggregateAndProofRequest_AggregateAndProof, using the provided AggregateAndProofRequestCapella
func (t *AggregateAndProofRequest_AggregateAndProof) MergeAggregateAndProofRequestCapella(v AggregateAndProofRequestCapella) error {
	v.Version = "CAPELLA"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAggregateAndProofRequestDeneb returns the union data inside the AggregateAndProofRequest_AggregateAndProof as a AggregateAndProofRequestDeneb
func (t AggregateAndProofRequest_AggregateAndProof) AsAggregateAndProofRequestDeneb() (AggregateAndProofRequestDeneb, error) {
	var body AggregateAndProofRequestDeneb
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAggregateAndProofRequestDeneb overwrites any union data inside the AggregateAndProofRequest_AggregateAndProof as the provided AggregateAndProofRequestDeneb
func (t *AggregateAndProofRequest_AggregateAndProof) FromAggregateAndProofRequestDeneb(v AggregateAndProofRequestDeneb) error {
	v.Version = "DENEB"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAggregateAndProofRequestDeneb performs a merge with any union data inside the AggregateAndProofRequest_AggregateAndProof, using the provided AggregateAndProofRequestDeneb
func (t *AggregateAndProofRequest_AggregateAndProof) MergeAggregateAndProofRequestDeneb(v AggregateAndProofRequestDeneb) error {
	v.Version = "DENEB"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAggregateAndProofRequestElectra returns the union data inside the AggregateAndProofRequest_AggregateAndProof as a AggregateAndProofRequestElectra
func (t AggregateAndProofRequest_AggregateAndProof) AsAggregateAndProofRequestElectra() (AggregateAndProofRequestElectra, error) {
	var body AggregateAndProofRequestElectra
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAggregateAndProofRequestElectra overwrites any union data inside the AggregateAndProofRequest_AggregateAndProof as the provided AggregateAndProofRequestElectra
func (t *AggregateAndProofRequest_AggregateAndProof) FromAggregateAndProofRequestElectra(v AggregateAndProofRequestElectra) error {
	v.Version = "ELECTRA"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAggregateAndProofRequestElectra performs a merge with any union data inside the AggregateAndProofRequest_AggregateAndProof, using the provided AggregateAndProofRequestElectra
func (t *AggregateAndProofRequest_AggregateAndProof) MergeAggregateAndProofRequestElectra(v AggregateAndProofRequestElectra) error {
	v.Version = "ELECTRA"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAggregateAndProofRequestFulu returns the union data inside the AggregateAndProofRequest_AggregateAndProof as a AggregateAndProofRequestFulu
func (t AggregateAndProofRequest_AggregateAndProof) AsAggregateAndProofRequestFulu() (AggregateAndProofRequestFulu, error) {
	var body AggregateAndProofRequestFulu
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAggregateAndProofRequestFulu overwrites any union data inside the AggregateAndProofRequest_AggregateAndProof as the provided AggregateAndProofRequestFulu
func (t *AggregateAndProofRequest_AggregateAndProof) FromAggregateAndProofRequestFulu(v AggregateAndProofRequestFulu) error {
	v.Version = "FULU"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAggregateAndProofRequestFulu performs a merge with any union data inside the AggregateAndProofRequest_AggregateAndProof, using the provided AggregateAndProofRequestFulu
func (t *AggregateAndProofRequest_AggregateAndProof) MergeAggregateAndProofRequestFulu(v AggregateAndProofRequestFulu) error {
	v.Version = "FULU"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AggregateAndProofRequest_AggregateAndProof) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"version"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t AggregateAndProofRequest_AggregateAndProof) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ALTAIR":
		return t.AsAggregateAndProofRequestAltair()
	case "BELLATRIX":
		return t.AsAggregateAndProofRequestBellatrix()
	case "CAPELLA":
		return t.AsAggregateAndProofRequestCapella()
	case "DENEB":
		return t.AsAggregateAndProofRequestDeneb()
	case "ELECTRA":
		return t.AsAggregateAndProofRequestElectra()
	case "FULU":
		return t.AsAggregateAndProofRequestFulu()
	case "PHASE0":
		return t.AsAggregateAndProofRequestPhase0()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t AggregateAndProofRequest_AggregateAndProof) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AggregateAndProofRequest_AggregateAndProof) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsAggregateAndProofRequestPhase0 returns the union data inside the AggregateAndProofSigningV2_AggregateAndProof as a AggregateAndProofRequestPhase0
func (t AggregateAndProofSigningV2_AggregateAndProof) AsAggregateAndProofRequestPhase0() (AggregateAndProofRequestPhase0, error) {
	var body AggregateAndProofRequestPhase0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAggregateAndProofRequestPhase0 overwrites any union data inside the AggregateAndProofSigningV2_AggregateAndProof as the provided AggregateAndProofRequestPhase0
func (t *AggregateAndProofSigningV2_AggregateAndProof) FromAggregateAndProofRequestPhase0(v AggregateAndProofRequestPhase0) error {
	v.Version = "PHASE0"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAggregateAndProofRequestPhase0 performs a merge with any union data inside the AggregateAndProofSigningV2_AggregateAndProof, using the provided AggregateAndProofRequestPhase0
func (t *AggregateAndProofSigningV2_AggregateAndProof) MergeAggregateAndProofRequestPhase0(v AggregateAndProofRequestPhase0) error {
	v.Version = "PHASE0"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAggregateAndProofRequestAltair returns the union data inside the AggregateAndProofSigningV2_AggregateAndProof as a AggregateAndProofRequestAltair
func (t AggregateAndProofSigningV2_AggregateAndProof) AsAggregateAndProofRequestAltair() (AggregateAndProofRequestAltair, error) {
	var body AggregateAndProofRequestAltair
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAggregateAndProofRequestAltair overwrites any union data inside the AggregateAndProofSigningV2_AggregateAndProof as the provided AggregateAndProofRequestAltair
func (t *AggregateAndProofSigningV2_AggregateAndProof) FromAggregateAndProofRequestAltair(v AggregateAndProofRequestAltair) error {
	v.Version = "ALTAIR"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAggregateAndProofRequestAltair performs a merge with any union data inside the AggregateAndProofSigningV2_AggregateAndProof, using the provided AggregateAndProofRequestAltair
func (t *AggregateAndProofSigningV2_AggregateAndProof) MergeAggregateAndProofRequestAltair(v AggregateAndProofRequestAltair) error {
	v.Version = "ALTAIR"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAggregateAndProofRequestBellatrix returns the union data inside the AggregateAndProofSigningV2_AggregateAndProof as a AggregateAndProofRequestBellatrix
func (t AggregateAndProofSigningV2_AggregateAndProof) AsAggregateAndProofRequestBellatrix() (AggregateAndProofRequestBellatrix, error) {
	var body AggregateAndProofRequestBellatrix
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAggregateAndProofRequestBellatrix overwrites any union data inside the AggregateAndProofSigningV2_AggregateAndProof as the provided AggregateAndProofRequestBellatrix
func (t *AggregateAndProofSigningV2_AggregateAndProof) FromAggregateAndProofRequestBellatrix(v AggregateAndProofRequestBellatrix) error {
	v.Version = "BELLATRIX"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAggregateAndProofRequestBellatrix performs a merge with any union data inside the AggregateAndProofSigningV2_AggregateAndProof, using the provided AggregateAndProofRequestBellatrix
func (t *AggregateAndProofSigningV2_AggregateAndProof) MergeAggregateAndProofRequestBellatrix(v AggregateAndProofRequestBellatrix) error {
	v.Version = "BELLATRIX"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAggregateAndProofRequestCapella returns the union data inside the AggregateAndProofSigningV2_AggregateAndProof as a AggregateAndProofRequestCapella
func (t AggregateAndProofSigningV2_AggregateAndProof) AsAggregateAndProofRequestCapella() (AggregateAndProofRequestCapella, error) {
	var body AggregateAndProofRequestCapella
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAggregateAndProofRequestCapella overwrites any union data inside the AggregateAndProofSigningV2_AggregateAndProof as the provided AggregateAndProofRequestCapella
func (t *AggregateAndProofSigningV2_AggregateAndProof) FromAggregateAndProofRequestCapella(v AggregateAndProofRequestCapella) error {
	v.Version = "CAPELLA"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAggregateAndProofRequestCapella performs a merge with any union data inside the AggregateAndProofSigningV2_AggregateAndProof, using the provided AggregateAndProofRequestCapella
func (t *AggregateAndProofSigningV2_AggregateAndProof) MergeAggregateAndProofRequestCapella(v AggregateAndProofRequestCapella) error {
	v.Version = "CAPELLA"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAggregateAndProofRequestDeneb returns the union data inside the AggregateAndProofSigningV2_AggregateAndProof as a AggregateAndProofRequestDeneb
func (t AggregateAndProofSigningV2_AggregateAndProof) AsAggregateAndProofRequestDeneb() (AggregateAndProofRequestDeneb, error) {
	var body AggregateAndProofRequestDeneb
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAggregateAndProofRequestDeneb overwrites any union data inside the AggregateAndProofSigningV2_AggregateAndProof as the provided AggregateAndProofRequestDeneb
func (t *AggregateAndProofSigningV2_AggregateAndProof) FromAggregateAndProofRequestDeneb(v AggregateAndProofRequestDeneb) error {
	v.Version = "DENEB"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAggregateAndProofRequestDeneb performs a merge with any union data inside the AggregateAndProofSigningV2_AggregateAndProof, using the provided AggregateAndProofRequestDeneb
func (t *AggregateAndProofSigningV2_AggregateAndProof) MergeAggregateAndProofRequestDeneb(v AggregateAndProofRequestDeneb) error {
	v.Version = "DENEB"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAggregateAndProofRequestElectra returns the union data inside the AggregateAndProofSigningV2_AggregateAndProof as a AggregateAndProofRequestElectra
func (t AggregateAndProofSigningV2_AggregateAndProof) AsAggregateAndProofRequestElectra() (AggregateAndProofRequestElectra, error) {
	var body AggregateAndProofRequestElectra
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAggregateAndProofRequestElectra overwrites any union data inside the AggregateAndProofSigningV2_AggregateAndProof as the provided AggregateAndProofRequestElectra
func (t *AggregateAndProofSigningV2_AggregateAndProof) FromAggregateAndProofRequestElectra(v AggregateAndProofRequestElectra) error {
	v.Version = "ELECTRA"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAggregateAndProofRequestElectra performs a merge with any union data inside the AggregateAndProofSigningV2_AggregateAndProof, using the provided AggregateAndProofRequestElectra
func (t *AggregateAndProofSigningV2_AggregateAndProof) MergeAggregateAndProofRequestElectra(v AggregateAndProofRequestElectra) error {
	v.Version = "ELECTRA"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAggregateAndProofRequestFulu returns the union data inside the AggregateAndProofSigningV2_AggregateAndProof as a AggregateAndProofRequestFulu
func (t AggregateAndProofSigningV2_AggregateAndProof) AsAggregateAndProofRequestFulu() (AggregateAndProofRequestFulu, error) {
	var body AggregateAndProofRequestFulu
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAggregateAndProofRequestFulu overwrites any union data inside the AggregateAndProofSigningV2_AggregateAndProof as the provided AggregateAndProofRequestFulu
func (t *AggregateAndProofSigningV2_AggregateAndProof) FromAggregateAndProofRequestFulu(v AggregateAndProofRequestFulu) error {
	v.Version = "FULU"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAggregateAndProofRequestFulu performs a merge with any union data inside the AggregateAndProofSigningV2_AggregateAndProof, using the provided AggregateAndProofRequestFulu
func (t *AggregateAndProofSigningV2_AggregateAndProof) MergeAggregateAndProofRequestFulu(v AggregateAndProofRequestFulu) error {
	v.Version = "FULU"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AggregateAndProofSigningV2_AggregateAndProof) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"version"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t AggregateAndProofSigningV2_AggregateAndProof) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ALTAIR":
		return t.AsAggregateAndProofRequestAltair()
	case "BELLATRIX":
		return t.AsAggregateAndProofRequestBellatrix()
	case "CAPELLA":
		return t.AsAggregateAndProofRequestCapella()
	case "DENEB":
		return t.AsAggregateAndProofRequestDeneb()
	case "ELECTRA":
		return t.AsAggregateAndProofRequestElectra()
	case "FULU":
		return t.AsAggregateAndProofRequestFulu()
	case "PHASE0":
		return t.AsAggregateAndProofRequestPhase0()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t AggregateAndProofSigningV2_AggregateAndProof) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AggregateAndProofSigningV2_AggregateAndProof) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsBlockRequestPhase0 returns the union data inside the BeaconBlockRequest_BeaconBlock as a BlockRequestPhase0
func (t BeaconBlockRequest_BeaconBlock) AsBlockRequestPhase0() (BlockRequestPhase0, error) {
	var body BlockRequestPhase0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlockRequestPhase0 overwrites any union data inside the BeaconBlockRequest_BeaconBlock as the provided BlockRequestPhase0
func (t *BeaconBlockRequest_BeaconBlock) FromBlockRequestPhase0(v BlockRequestPhase0) error {
	v.Version = "PHASE0"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBlockRequestPhase0 performs a merge with any union data inside the BeaconBlockRequest_BeaconBlock, using the provided BlockRequestPhase0
func (t *BeaconBlockRequest_BeaconBlock) MergeBlockRequestPhase0(v BlockRequestPhase0) error {
	v.Version = "PHASE0"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBlockRequestAltair returns the union data inside the BeaconBlockRequest_BeaconBlock as a BlockRequestAltair
func (t BeaconBlockRequest_BeaconBlock) AsBlockRequestAltair() (BlockRequestAltair, error) {
	var body BlockRequestAltair
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlockRequestAltair overwrites any union data inside the BeaconBlockRequest_BeaconBlock as the provided BlockRequestAltair
func (t *BeaconBlockRequest_BeaconBlock) FromBlockRequestAltair(v BlockRequestAltair) error {
	v.Version = "ALTAIR"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBlockRequestAltair performs a merge with any union data inside the BeaconBlockRequest_BeaconBlock, using the provided BlockRequestAltair
func (t *BeaconBlockRequest_BeaconBlock) MergeBlockRequestAltair(v BlockRequestAltair) error {
	v.Version = "ALTAIR"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBlockRequestBellatrix returns the union data inside the BeaconBlockRequest_BeaconBlock as a BlockRequestBellatrix
func (t BeaconBlockRequest_BeaconBlock) AsBlockRequestBellatrix() (BlockRequestBellatrix, error) {
	var body BlockRequestBellatrix
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlockRequestBellatrix overwrites any union data inside the BeaconBlockRequest_BeaconBlock as the provided BlockRequestBellatrix
func (t *BeaconBlockRequest_BeaconBlock) FromBlockRequestBellatrix(v BlockRequestBellatrix) error {
	v.Version = "BELLATRIX"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBlockRequestBellatrix performs a merge with any union data inside the BeaconBlockRequest_BeaconBlock, using the provided BlockRequestBellatrix
func (t *BeaconBlockRequest_BeaconBlock) MergeBlockRequestBellatrix(v BlockRequestBellatrix) error {
	v.Version = "BELLATRIX"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBlockRequestCapella returns the union data inside the BeaconBlockRequest_BeaconBlock as a BlockRequestCapella
func (t BeaconBlockRequest_BeaconBlock) AsBlockRequestCapella() (BlockRequestCapella, error) {
	var body BlockRequestCapella
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlockRequestCapella overwrites any union data inside the BeaconBlockRequest_BeaconBlock as the provided BlockRequestCapella
func (t *BeaconBlockRequest_BeaconBlock) FromBlockRequestCapella(v BlockRequestCapella) error {
	v.Version = "CAPELLA"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBlockRequestCapella performs a merge with any union data inside the BeaconBlockRequest_BeaconBlock, using the provided BlockRequestCapella
func (t *BeaconBlockRequest_BeaconBlock) MergeBlockRequestCapella(v BlockRequestCapella) error {
	v.Version = "CAPELLA"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBlockRequestDeneb returns the union data inside the BeaconBlockRequest_BeaconBlock as a BlockRequestDeneb
func (t BeaconBlockRequest_BeaconBlock) AsBlockRequestDeneb() (BlockRequestDeneb, error) {
	var body BlockRequestDeneb
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlockRequestDeneb overwrites any union data inside the BeaconBlockRequest_BeaconBlock as the provided BlockRequestDeneb
func (t *BeaconBlockRequest_BeaconBlock) FromBlockRequestDeneb(v BlockRequestDeneb) error {
	v.Version = "DENEB"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBlockRequestDeneb performs a merge with any union data inside the BeaconBlockRequest_BeaconBlock, using the provided BlockRequestDeneb
func (t *BeaconBlockRequest_BeaconBlock) MergeBlockRequestDeneb(v BlockRequestDeneb) error {
	v.Version = "DENEB"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBlockRequestElectra returns the union data inside the BeaconBlockRequest_BeaconBlock as a BlockRequestElectra
func (t BeaconBlockRequest_BeaconBlock) AsBlockRequestElectra() (BlockRequestElectra, error) {
	var body BlockRequestElectra
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlockRequestElectra overwrites any union data inside the BeaconBlockRequest_BeaconBlock as the provided BlockRequestElectra
func (t *BeaconBlockRequest_BeaconBlock) FromBlockRequestElectra(v BlockRequestElectra) error {
	v.Version = "ELECTRA"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBlockRequestElectra performs a merge with any union data inside the BeaconBlockRequest_BeaconBlock, using the provided BlockRequestElectra
func (t *BeaconBlockRequest_BeaconBlock) MergeBlockRequestElectra(v BlockRequestElectra) error {
	v.Version = "ELECTRA"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBlockRequestFulu returns the union data inside the BeaconBlockRequest_BeaconBlock as a BlockRequestFulu
func (t BeaconBlockRequest_BeaconBlock) AsBlockRequestFulu() (BlockRequestFulu, error) {
	var body BlockRequestFulu
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlockRequestFulu overwrites any union data inside the BeaconBlockRequest_BeaconBlock as the provided BlockRequestFulu
func (t *BeaconBlockRequest_BeaconBlock) FromBlockRequestFulu(v BlockRequestFulu) error {
	v.Version = "FULU"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBlockRequestFulu performs a merge with any union data inside the BeaconBlockRequest_BeaconBlock, using the provided BlockRequestFulu
func (t *BeaconBlockRequest_BeaconBlock) MergeBlockRequestFulu(v BlockRequestFulu) error {
	v.Version = "FULU"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t BeaconBlockRequest_BeaconBlock) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"version"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t BeaconBlockRequest_BeaconBlock) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ALTAIR":
		return t.AsBlockRequestAltair()
	case "BELLATRIX":
		return t.AsBlockRequestBellatrix()
	case "CAPELLA":
		return t.AsBlockRequestCapella()
	case "DENEB":
		return t.AsBlockRequestDeneb()
	case "ELECTRA":
		return t.AsBlockRequestElectra()
	case "FULU":
		return t.AsBlockRequestFulu()
	case "PHASE0":
		return t.AsBlockRequestPhase0()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t BeaconBlockRequest_BeaconBlock) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *BeaconBlockRequest_BeaconBlock) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsBlockRequestPhase0 returns the union data inside the BeaconBlockSigning_BeaconBlock as a BlockRequestPhase0
func (t BeaconBlockSigning_BeaconBlock) AsBlockRequestPhase0() (BlockRequestPhase0, error) {
	var body BlockRequestPhase0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlockRequestPhase0 overwrites any union data inside the BeaconBlockSigning_BeaconBlock as the provided BlockRequestPhase0
func (t *BeaconBlockSigning_BeaconBlock) FromBlockRequestPhase0(v BlockRequestPhase0) error {
	v.Version = "PHASE0"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBlockRequestPhase0 performs a merge with any union data inside the BeaconBlockSigning_BeaconBlock, using the provided BlockRequestPhase0
func (t *BeaconBlockSigning_BeaconBlock) MergeBlockRequestPhase0(v BlockRequestPhase0) error {
	v.Version = "PHASE0"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBlockRequestAltair returns the union data inside the BeaconBlockSigning_BeaconBlock as a BlockRequestAltair
func (t BeaconBlockSigning_BeaconBlock) AsBlockRequestAltair() (BlockRequestAltair, error) {
	var body BlockRequestAltair
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlockRequestAltair overwrites any union data inside the BeaconBlockSigning_BeaconBlock as the provided BlockRequestAltair
func (t *BeaconBlockSigning_BeaconBlock) FromBlockRequestAltair(v BlockRequestAltair) error {
	v.Version = "ALTAIR"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBlockRequestAltair performs a merge with any union data inside the BeaconBlockSigning_BeaconBlock, using the provided BlockRequestAltair
func (t *BeaconBlockSigning_BeaconBlock) MergeBlockRequestAltair(v BlockRequestAltair) error {
	v.Version = "ALTAIR"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBlockRequestBellatrix returns the union data inside the BeaconBlockSigning_BeaconBlock as a BlockRequestBellatrix
func (t BeaconBlockSigning_BeaconBlock) AsBlockRequestBellatrix() (BlockRequestBellatrix, error) {
	var body BlockRequestBellatrix
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlockRequestBellatrix overwrites any union data inside the BeaconBlockSigning_BeaconBlock as the provided BlockRequestBellatrix
func (t *BeaconBlockSigning_BeaconBlock) FromBlockRequestBellatrix(v BlockRequestBellatrix) error {
	v.Version = "BELLATRIX"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBlockRequestBellatrix performs a merge with any union data inside the BeaconBlockSigning_BeaconBlock, using the provided BlockRequestBellatrix
func (t *BeaconBlockSigning_BeaconBlock) MergeBlockRequestBellatrix(v BlockRequestBellatrix) error {
	v.Version = "BELLATRIX"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBlockRequestCapella returns the union data inside the BeaconBlockSigning_BeaconBlock as a BlockRequestCapella
func (t BeaconBlockSigning_BeaconBlock) AsBlockRequestCapella() (BlockRequestCapella, error) {
	var body BlockRequestCapella
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlockRequestCapella overwrites any union data inside the BeaconBlockSigning_BeaconBlock as the provided BlockRequestCapella
func (t *BeaconBlockSigning_BeaconBlock) FromBlockRequestCapella(v BlockRequestCapella) error {
	v.Version = "CAPELLA"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBlockRequestCapella performs a merge with any union data inside the BeaconBlockSigning_BeaconBlock, using the provided BlockRequestCapella
func (t *BeaconBlockSigning_BeaconBlock) MergeBlockRequestCapella(v BlockRequestCapella) error {
	v.Version = "CAPELLA"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBlockRequestDeneb returns the union data inside the BeaconBlockSigning_BeaconBlock as a BlockRequestDeneb
func (t BeaconBlockSigning_BeaconBlock) AsBlockRequestDeneb() (BlockRequestDeneb, error) {
	var body BlockRequestDeneb
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlockRequestDeneb overwrites any union data inside the BeaconBlockSigning_BeaconBlock as the provided BlockRequestDeneb
func (t *BeaconBlockSigning_BeaconBlock) FromBlockRequestDeneb(v BlockRequestDeneb) error {
	v.Version = "DENEB"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBlockRequestDeneb performs a merge with any union data inside the BeaconBlockSigning_BeaconBlock, using the provided BlockRequestDeneb
func (t *BeaconBlockSigning_BeaconBlock) MergeBlockRequestDeneb(v BlockRequestDeneb) error {
	v.Version = "DENEB"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBlockRequestElectra returns the union data inside the BeaconBlockSigning_BeaconBlock as a BlockRequestElectra
func (t BeaconBlockSigning_BeaconBlock) AsBlockRequestElectra() (BlockRequestElectra, error) {
	var body BlockRequestElectra
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlockRequestElectra overwrites any union data inside the BeaconBlockSigning_BeaconBlock as the provided BlockRequestElectra
func (t *BeaconBlockSigning_BeaconBlock) FromBlockRequestElectra(v BlockRequestElectra) error {
	v.Version = "ELECTRA"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBlockRequestElectra performs a merge with any union data inside the BeaconBlockSigning_BeaconBlock, using the provided BlockRequestElectra
func (t *BeaconBlockSigning_BeaconBlock) MergeBlockRequestElectra(v BlockRequestElectra) error {
	v.Version = "ELECTRA"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBlockRequestFulu returns the union data inside the BeaconBlockSigning_BeaconBlock as a BlockRequestFulu
func (t BeaconBlockSigning_BeaconBlock) AsBlockRequestFulu() (BlockRequestFulu, error) {
	var body BlockRequestFulu
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlockRequestFulu overwrites any union data inside the BeaconBlockSigning_BeaconBlock as the provided BlockRequestFulu
func (t *BeaconBlockSigning_BeaconBlock) FromBlockRequestFulu(v BlockRequestFulu) error {
	v.Version = "FULU"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBlockRequestFulu performs a merge with any union data inside the BeaconBlockSigning_BeaconBlock, using the provided BlockRequestFulu
func (t *BeaconBlockSigning_BeaconBlock) MergeBlockRequestFulu(v BlockRequestFulu) error {
	v.Version = "FULU"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t BeaconBlockSigning_BeaconBlock) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"version"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t BeaconBlockSigning_BeaconBlock) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ALTAIR":
		return t.AsBlockRequestAltair()
	case "BELLATRIX":
		return t.AsBlockRequestBellatrix()
	case "CAPELLA":
		return t.AsBlockRequestCapella()
	case "DENEB":
		return t.AsBlockRequestDeneb()
	case "ELECTRA":
		return t.AsBlockRequestElectra()
	case "FULU":
		return t.AsBlockRequestFulu()
	case "PHASE0":
		return t.AsBlockRequestPhase0()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t BeaconBlockSigning_BeaconBlock) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *BeaconBlockSigning_BeaconBlock) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
