// Code generated by signablegen; DO NOT EDIT.

package api

import (
	"context"
	"fmt"

	"github.com/jshufro/remote-signer-dirk-interop/internal/errors"

	apiv1 "github.com/attestantio/go-eth2-client/api/v1"
	"github.com/attestantio/go-eth2-client/spec/altair"
	"github.com/attestantio/go-eth2-client/spec/electra"
	"github.com/attestantio/go-eth2-client/spec/phase0"
)

type AggregateAndProofElectra = electra.AggregateAndProof
type AggregateAndProofPhase0 = phase0.AggregateAndProof
type AttestationData = phase0.AttestationData
type BeaconBlock = phase0.BeaconBlock
type BeaconBlockAltair = altair.BeaconBlock
type BeaconBlockHeader = phase0.BeaconBlockHeader
type ContributionAndProof = altair.ContributionAndProof
type SyncAggregatorSelectionData = altair.SyncAggregatorSelectionData
type SyncCommitteeMessage = altair.SyncCommitteeMessage
type ValidatorRegistration = apiv1.ValidatorRegistration
type VoluntaryExit = phase0.VoluntaryExit

// Signer combines all signable request types from the remote signing API.
type Signer interface {
	AggregationSlotSigning(context.Context, [48]byte, *AggregationSlotSigning) ([96]byte, *errors.SignerError)
	AggregateAndProofSigningV2(context.Context, [48]byte, *AggregateAndProofSigningV2) ([96]byte, *errors.SignerError)
	AttestationSigning(context.Context, [48]byte, *AttestationSigning) ([96]byte, *errors.SignerError)
	BeaconBlockSigning(context.Context, [48]byte, *BeaconBlockSigning) ([96]byte, *errors.SignerError)
	DepositSigning(context.Context, [48]byte, *DepositSigning) ([96]byte, *errors.SignerError)
	RandaoRevealSigning(context.Context, [48]byte, *RandaoRevealSigning) ([96]byte, *errors.SignerError)
	VoluntaryExitSigning(context.Context, [48]byte, *VoluntaryExitSigning) ([96]byte, *errors.SignerError)
	SyncCommitteeMessageSigning(context.Context, [48]byte, *SyncCommitteeMessageSigning) ([96]byte, *errors.SignerError)
	SyncCommitteeSelectionProofSigning(context.Context, [48]byte, *SyncCommitteeSelectionProofSigning) ([96]byte, *errors.SignerError)
	SyncCommitteeContributionAndProofSigning(context.Context, [48]byte, *SyncCommitteeContributionAndProofSigning) ([96]byte, *errors.SignerError)
	ValidatorRegistrationSigning(context.Context, [48]byte, *ValidatorRegistrationSigning) ([96]byte, *errors.SignerError)
}

// StringToSignableType converts a discriminator string to a signable type.
func StringToSignableType(discriminator string) (any, error) {
	switch discriminator {
	case "AGGREGATE_AND_PROOF_V2":
		return &AggregateAndProofSigningV2{}, nil
	case "AGGREGATION_SLOT":
		return &AggregationSlotSigning{}, nil
	case "ATTESTATION":
		return &AttestationSigning{}, nil
	case "BLOCK_V2":
		return &BeaconBlockSigning{}, nil
	case "DEPOSIT":
		return &DepositSigning{}, nil
	case "RANDAO_REVEAL":
		return &RandaoRevealSigning{}, nil
	case "SYNC_COMMITTEE_CONTRIBUTION_AND_PROOF":
		return &SyncCommitteeContributionAndProofSigning{}, nil
	case "SYNC_COMMITTEE_MESSAGE":
		return &SyncCommitteeMessageSigning{}, nil
	case "SYNC_COMMITTEE_SELECTION_PROOF":
		return &SyncCommitteeSelectionProofSigning{}, nil
	case "VALIDATOR_REGISTRATION":
		return &ValidatorRegistrationSigning{}, nil
	case "VOLUNTARY_EXIT":
		return &VoluntaryExitSigning{}, nil
	default:
		return nil, fmt.Errorf("unknown discriminator value: %s", discriminator)
	}
}

// Sign calls the appropriate sign method based on the type of the signable.
func Sign(ctx context.Context, signer Signer, publicKey [48]byte, signable any) ([96]byte, *errors.SignerError) {
	switch signable := signable.(type) {
	case *AggregationSlotSigning:
		return signer.AggregationSlotSigning(ctx, publicKey, signable)
	case *AggregateAndProofSigningV2:
		return signer.AggregateAndProofSigningV2(ctx, publicKey, signable)
	case *AttestationSigning:
		return signer.AttestationSigning(ctx, publicKey, signable)
	case *BeaconBlockSigning:
		return signer.BeaconBlockSigning(ctx, publicKey, signable)
	case *DepositSigning:
		return signer.DepositSigning(ctx, publicKey, signable)
	case *RandaoRevealSigning:
		return signer.RandaoRevealSigning(ctx, publicKey, signable)
	case *VoluntaryExitSigning:
		return signer.VoluntaryExitSigning(ctx, publicKey, signable)
	case *SyncCommitteeMessageSigning:
		return signer.SyncCommitteeMessageSigning(ctx, publicKey, signable)
	case *SyncCommitteeSelectionProofSigning:
		return signer.SyncCommitteeSelectionProofSigning(ctx, publicKey, signable)
	case *SyncCommitteeContributionAndProofSigning:
		return signer.SyncCommitteeContributionAndProofSigning(ctx, publicKey, signable)
	case *ValidatorRegistrationSigning:
		return signer.ValidatorRegistrationSigning(ctx, publicKey, signable)
	default:
		return [96]byte{}, errors.ErrInternalServerError
	}
}
