// Code generated by signablegen; DO NOT EDIT.

package api

import (
	"context"
)

// Signer combines all signable request types from the remote signing API.
type Signer interface {
	SignAggregationSlotSigning(context.Context, *AggregationSlotSigning) ([96]byte, error)
	SignAggregateAndProofSigning(context.Context, *AggregateAndProofSigning) ([96]byte, error)
	SignAggregateAndProofSigningV2(context.Context, *AggregateAndProofSigningV2) ([96]byte, error)
	SignAttestationSigning(context.Context, *AttestationSigning) ([96]byte, error)
	SignBlockSigning(context.Context, *BlockSigning) ([96]byte, error)
	SignBeaconBlockSigning(context.Context, *BeaconBlockSigning) ([96]byte, error)
	SignDepositSigning(context.Context, *DepositSigning) ([96]byte, error)
	SignRandaoRevealSigning(context.Context, *RandaoRevealSigning) ([96]byte, error)
	SignVoluntaryExitSigning(context.Context, *VoluntaryExitSigning) ([96]byte, error)
	SignSyncCommitteeMessageSigning(context.Context, *SyncCommitteeMessageSigning) ([96]byte, error)
	SignSyncCommitteeSelectionProofSigning(context.Context, *SyncCommitteeSelectionProofSigning) ([96]byte, error)
	SignSyncCommitteeContributionAndProofSigning(context.Context, *SyncCommitteeContributionAndProofSigning) ([96]byte, error)
	SignValidatorRegistrationSigning(context.Context, *ValidatorRegistrationSigning) ([96]byte, error)
}
