{
 "title": "Dirk Interop",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "quantiles", "query": "95,75,50,25,5" }
  ]
 },
 "panels": [
  {
   "title": "Up/Down",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    { "expr": "remote_signer_dirk_interop_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Interop Uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-remote_signer_dirk_interop_start_time",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Signing Latency - $quantiles",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "repeat": "quantiles",
   "targets": [
    {
     "expr": "histogram_quantile($quantiles/100, sum(rate(remote_signer_dirk_interop_sign_duration_seconds_bucket[$__rate_interval])) by (le, signable_type))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Signing Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum (increase(remote_signer_dirk_interop_sign_requests_total{}[$__rate_interval])) by (signable_type)",
     "legendFormat": "{{signable_type}}"
    }
   ]
  },
  {
   "title": "Public Keys Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(remote_signer_dirk_interop_public_keys_requests_total{}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Signing Response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum (increase(remote_signer_dirk_interop_sign_response_counts{status_code=\"200\"}[$__rate_interval])) by (signable_type)",
     "legendFormat": "{{signable_type}}"
    },
    {
     "expr": "-sum (increase(remote_signer_dirk_interop_sign_response_counts{status_code!=\"200\"}[$__rate_interval])) by (signable_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Public Keys Response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(remote_signer_dirk_interop_public_keys_response_counts{status_code=\"200\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "-sum(increase(remote_signer_dirk_interop_public_keys_response_counts{status_code!=\"200\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Signing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Signing 200 OK ",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum (increase(remote_signer_dirk_interop_sign_response_counts{status_code=\"200\"}[$__rate_interval])) by (signable_type)",
     "legendFormat": "{{signable_type}}"
    }
   ]
  },
  {
   "title": "Signing Error",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 37 },
   "targets": [
    {
     "expr": "sum (increase(remote_signer_dirk_interop_sign_response_counts{status_code!=\"200\"}[$__rate_interval])) by (status_code, signable_type)",
     "legendFormat": "{{signable_type}} {{status_code}}"
    }
   ]
  }
 ]
}