package main

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	if len(os.Args) != 4 {
		log.Fatalf("usage: %s <pkgname> <sign.yaml> <dst.go>", os.Args[0])
	}

	// schemasPath is currently unused but kept for the intended interface.
	// It can be used in the future to validate that referenced schemas exist.
	pkgname := os.Args[1]
	signPath := os.Args[2]
	dst := os.Args[3]

	data, err := os.ReadFile(signPath)
	if err != nil {
		log.Fatalf("reading sign.yaml: %v", err)
	}

	var root map[string]any
	if err := yaml.Unmarshal(data, &root); err != nil {
		log.Fatalf("parsing sign.yaml: %v", err)
	}

	schema, err := extractSchema(root)
	if err != nil {
		log.Fatalf("extracting schema from sign.yaml: %v", err)
	}

	discriminatorMapping, err := extractDiscriminatorMapping(schema)
	if err != nil {
		log.Fatalf("extracting discriminator mapping from sign.yaml: %v", err)
	}

	oneOf, err := extractOneOf(schema)
	if err != nil {
		log.Fatalf("extracting oneOf from sign.yaml: %v", err)
	}

	schemaNames := schemaNamesFromRefs(oneOf)
	if len(schemaNames) == 0 {
		log.Fatalf("no schemas found under post.requestBody.content.application/json.schema.oneOf")
	}

	discriminatorsToTypes, err := discriminatorMappingToTypes(discriminatorMapping)
	if err != nil {
		log.Fatalf("extracting discriminator mapping to types: %v", err)
	}
	if len(discriminatorsToTypes) == 0 {
		log.Fatalf("no discriminator mapping found")
	}

	if len(discriminatorsToTypes) != len(schemaNames) {
		log.Fatalf("number of discriminator mappings does not match number of schemas")
	}

	if err := emitGo(pkgname, schemaNames, discriminatorsToTypes, dst); err != nil {
		log.Fatalf("emitting Go: %v", err)
	}
}

func extractSchema(root map[string]any) (map[string]any, error) {
	post, ok := root["post"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("missing or invalid 'post' object")
	}

	requestBody, ok := post["requestBody"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("missing or invalid 'post.requestBody'")
	}

	content, ok := requestBody["content"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("missing or invalid 'post.requestBody.content'")
	}

	appJSON, ok := content["application/json"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("missing or invalid 'post.requestBody.content.application/json'")
	}

	schema, ok := appJSON["schema"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("missing or invalid '...application/json.schema'")
	}
	return schema, nil
}

func extractDiscriminatorMapping(schema map[string]any) (map[string]any, error) {
	rawDiscriminator, ok := schema["discriminator"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("missing or invalid '...schema.discriminator'")
	}

	discriminatorMapping, ok := rawDiscriminator["mapping"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("missing or invalid '...schema.discriminator.mapping'")
	}

	return discriminatorMapping, nil
}

func extractOneOf(schema map[string]any) ([]any, error) {

	rawOneOf, ok := schema["oneOf"].([]any)
	if !ok {
		return nil, fmt.Errorf("missing or invalid '...schema.oneOf'")
	}

	return rawOneOf, nil
}

func refToName(ref string) string {
	lastSlash := strings.LastIndex(ref, "/")
	if lastSlash == -1 || lastSlash+1 >= len(ref) {
		return ""
	}
	return ref[lastSlash+1:]
}

func schemaNamesFromRefs(oneOf []any) []string {
	seen := make(map[string]struct{})
	var out []string

	for _, item := range oneOf {
		m, ok := item.(map[string]any)
		if !ok {
			continue
		}
		ref, ok := m["$ref"].(string)
		if !ok || ref == "" {
			continue
		}

		name := refToName(ref)
		if name == "" {
			continue
		}

		if _, exists := seen[name]; exists {
			continue
		}
		seen[name] = struct{}{}
		out = append(out, name)
	}

	return out
}

func discriminatorMappingToTypes(discriminatorMapping map[string]any) (map[string]string, error) {
	types := make(map[string]string)
	for discriminator, schema := range discriminatorMapping {
		schemaStr, ok := schema.(string)
		if !ok {
			return nil, fmt.Errorf("invalid schema type: %T", schema)
		}

		types[discriminator] = refToName(schemaStr)
	}
	return types, nil
}

func emitGo(pkgname string, schemaNames []string, discriminatorsToTypes map[string]string, dst string) error {
	var buf bytes.Buffer

	write := func(s string) {
		if _, err := buf.WriteString(s); err != nil {
			// bytes.Buffer.WriteString currently never returns an error,
			// but handle it defensively.
			panic(fmt.Errorf("writing generated buffer: %w", err))
		}
	}
	writef := func(format string, args ...any) {
		if _, err := fmt.Fprintf(&buf, format, args...); err != nil {
			// fmt.Fprintf to bytes.Buffer should not fail under normal circumstances.
			panic(fmt.Errorf("writing generated buffer: %w", err))
		}
	}

	write("// Code generated by signablegen; DO NOT EDIT.\n\n")
	writef("package %s\n\n", pkgname)

	write("import (\n")
	write("\t\"context\"\n")
	write("\t\"fmt\"\n")
	write(")\n\n")

	write("// Signer combines all signable request types from the remote signing API.\n")
	write("type Signer interface {\n")
	for _, name := range schemaNames {
		writef("\t%s(context.Context, *%s) ([96]byte, error)\n", name, name)
	}
	write("}\n\n")

	write("// StringToSignableType converts a discriminator string to a signable type.\n")
	write("func StringToSignableType(discriminator string) (any, error) {\n")
	write("\tswitch discriminator {\n")

	discriminators := make([]string, 0, len(discriminatorsToTypes))
	for discriminator := range discriminatorsToTypes {
		discriminators = append(discriminators, discriminator)
	}
	sort.Strings(discriminators)

	for _, discriminator := range discriminators {
		name := discriminatorsToTypes[discriminator]
		writef("\tcase %q:\n", discriminator)
		writef("\t\treturn &%s{}, nil\n", name)
	}

	write("\tdefault:\n")
	write("\t\treturn nil, fmt.Errorf(\"unknown discriminator value: %s\", discriminator)\n")
	write("\t}\n")
	write("}\n\n")

	write("// Sign calls the appropriate sign method based on the type of the signable.\n")
	write("func Sign(ctx context.Context, signer Signer, signable any) ([96]byte, error) {\n")
	write("\tswitch signable := signable.(type) {\n")

	for _, name := range schemaNames {
		writef("\tcase *%s:\n", name)
		writef("\t\treturn signer.%s(ctx, signable)\n", name)
	}

	write("\tdefault:\n")
	write("\t\treturn [96]byte{}, fmt.Errorf(\"unknown signable type: %T\", signable)\n")
	write("\t}\n")
	write("}\n")

	f, err := os.Create(dst)
	if err != nil {
		return fmt.Errorf("creating %s: %w", dst, err)
	}
	defer func() {
		_ = f.Close()
	}()

	if _, err := io.Copy(f, &buf); err != nil {
		return fmt.Errorf("writing %s: %w", dst, err)
	}

	return nil
}
