package main

import (
	"fmt"
	"log"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

// main is a small code generator which:
//   - Takes two arguments: the path to schemas.yaml and the path to sign.yaml
//   - Parses sign.yaml and extracts the schema names from:
//     post.requestBody.content.application/json.schema.oneOf
//   - Emits Go code to stdout defining:
//     type Signable[T any] interface {
//     Sign(ctx context.Context, signable *T) ([96]byte, error)
//     }
//     type Signer interface {
//     Signable[api.<SchemaName1>]
//     Signable[api.<SchemaName2>]
//     ...
//     }
//
// The generated code is intended to live in the dirksigner package and use the
// api types from internal/api. Run it like:
//
//	go run ./signablegen ../remote-signing-api/signing/schemas.yaml ../remote-signing-api/signing/paths/sign.yaml > pkg/signer/signables.gen.go
func main() {
	if len(os.Args) != 4 {
		log.Fatalf("usage: %s <pkgname> <sign.yaml> <dst.go>", os.Args[0])
	}

	// schemasPath is currently unused but kept for the intended interface.
	// It can be used in the future to validate that referenced schemas exist.
	pkgname := os.Args[1]
	signPath := os.Args[2]
	dst := os.Args[3]

	data, err := os.ReadFile(signPath)
	if err != nil {
		log.Fatalf("reading sign.yaml: %v", err)
	}

	var root map[string]any
	if err := yaml.Unmarshal(data, &root); err != nil {
		log.Fatalf("parsing sign.yaml: %v", err)
	}

	oneOf, err := extractOneOf(root)
	if err != nil {
		log.Fatalf("extracting oneOf from sign.yaml: %v", err)
	}

	schemaNames := schemaNamesFromRefs(oneOf)
	if len(schemaNames) == 0 {
		log.Fatalf("no schemas found under post.requestBody.content.application/json.schema.oneOf")
	}

	if err := emitGo(pkgname, schemaNames, dst); err != nil {
		log.Fatalf("emitting Go: %v", err)
	}
}

// extractOneOf navigates the parsed sign.yaml structure to the
// post.requestBody.content.application/json.schema.oneOf node.
func extractOneOf(root map[string]any) ([]any, error) {
	post, ok := root["post"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("missing or invalid 'post' object")
	}

	requestBody, ok := post["requestBody"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("missing or invalid 'post.requestBody'")
	}

	content, ok := requestBody["content"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("missing or invalid 'post.requestBody.content'")
	}

	appJSON, ok := content["application/json"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("missing or invalid 'post.requestBody.content.application/json'")
	}

	schema, ok := appJSON["schema"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("missing or invalid '...application/json.schema'")
	}

	rawOneOf, ok := schema["oneOf"].([]any)
	if !ok {
		return nil, fmt.Errorf("missing or invalid '...schema.oneOf'")
	}

	return rawOneOf, nil
}

// schemaNamesFromRefs extracts schema names from a oneOf array of $ref objects.
// Each element is expected to look like:
//
//	{ "$ref": "../schemas.yaml#/components/schemas/AggregationSlotSigning" }
func schemaNamesFromRefs(oneOf []any) []string {
	seen := make(map[string]struct{})
	var out []string

	for _, item := range oneOf {
		m, ok := item.(map[string]any)
		if !ok {
			continue
		}
		ref, ok := m["$ref"].(string)
		if !ok || ref == "" {
			continue
		}

		// Take the part after the last '/' – this is the schema name.
		lastSlash := strings.LastIndex(ref, "/")
		if lastSlash == -1 || lastSlash+1 >= len(ref) {
			continue
		}
		name := ref[lastSlash+1:]
		if name == "" {
			continue
		}

		if _, exists := seen[name]; exists {
			continue
		}
		seen[name] = struct{}{}
		out = append(out, name)
	}

	return out
}

// emitGo writes the generated Go code to stdout.
//
// It assumes:
//   - The target package is `signer`
//   - The remote signing types live in `github.com/jshufro/remote-signer-dirk-interop/internal/api`
func emitGo(pkgname string, schemaNames []string, dst string) error {
	// Get the deepest directory name from the dst path
	f, err := os.Create(dst)
	if err != nil {
		return fmt.Errorf("creating %s: %w", dst, err)
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by signablegen; DO NOT EDIT.")
	fmt.Fprintln(f)
	fmt.Fprintf(f, "package %s\n", pkgname)
	fmt.Fprintln(f)
	fmt.Fprintln(f, "import (")
	fmt.Fprintln(f, "\t\"context\"")
	fmt.Fprintln(f, ")")
	fmt.Fprintln(f)

	fmt.Fprintln(f, "// Signer combines all signable request types from the remote signing API.")
	fmt.Fprintln(f, "type Signer interface {")
	for _, name := range schemaNames {
		fmt.Fprintf(f, "\tSign%s(context.Context, *%s) ([96]byte, error)\n", name, name)
	}
	fmt.Fprintln(f, "}")

	return nil
}
